server:
  port:
    8089
  use-forward-headers:
    true
spring:
  application:
    name: fintrack
  datasource:
    url: jdbc:postgresql://localhost:5432/finTrack
    username: postgres
    password: Tejas@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      username: user
      password: user
    oauth2:
      client:
        registration:
          google:
            client-id: 16591967139-cgecre92o500ih9e1g56a9d5vrs51h0u.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23liJP6IG2eTHxXrln
            client-secret: 69e51e1a838539f5123e6d8124e73e54cee7e201
            scope: read:user,user:email
frontend-url: "http://localhost:5173"
