#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: fintrack
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Root
#    ports:
#      - "5432:5432"
#    volumes:
#      - my_dbdata:/var/lib/postgresql/data
#
#volumes:
#  my_dbdata:
