version: "3.8"

services:
  fastapi_app:
    image: fintrack/fintrack-ai:latest
    container_name: fintrack-ai
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    restart: always
